# Generated by Django 5.2.7 on 2025-11-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regmarket_app', '0004_profile_first_name_profile_image_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='market_backgrounds/%y/%m/%d/'),
        ),
    ]
